name: First Experiment
on:
  push:
  
jobs:
  testing-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: npm install
        env:
          CI: true
        run:  |
          npm ci
      - name: Install xmllint
	run: sudo apt-get install libxml2-utils

