name: GITHUBACTION
on: 
  push:
      branches:
        - '*'
        - '!master'
        
jobs:
  phptest:
    name: "Github Action"
    runs-on: ubuntu-latest
    steps:
      - name: "check the repo"
        uses: action/checkout@v2
  
