name: my workflow
on: 
  push:
  pull_request:

jobs:
  test-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test packages
        run: echo "Running tests"
  deploy-packages:
    if: startsWith(github.ref,  'refs/tags/v')
    runs-on: ubuntu-latest
    needs: test-packages
    steps:
      - uses: actions/checkout@v2
      - name: deploy packages
        run: echo "Deploying packages"
