name: "GITHUB ACTIONS"
on: 
  push:
    branches:
      - '*'

jobs:
  nodejstest:
    name: "Nodejs Test"
    runs-on: ubuntu-latest
    steps:
      - name: "Github actions store ssh_key"
        run: |
          'echo "$SSH_KEY" > key'
        shell: bash
        env:
          SSH_KEY: ${{secrets.SSH_KEY}}
